# Generated by Django 2.0.9 on 2025-03-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('complaints', models.CharField(max_length=250)),
                ('replay', models.CharField(max_length=100)),
                ('replay_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UName', models.CharField(max_length=100)),
                ('Ratings', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SName', models.CharField(max_length=100)),
                ('WName', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=250)),
                ('Contact', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workerapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workerapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='WORKER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workerapp.worker'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workerapp.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workerapp.login'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workerapp.user'),
        ),
    ]
