# Generated by Django 2.0.9 on 2025-03-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicerequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='UName',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Contact',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='WName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='password',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='username',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='SERVICE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workerapp.service'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workerapp.user'),
        ),
    ]
