# Generated by Django 2.0.9 on 2025-03-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0002_auto_20250312_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='WORKER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workerapp.worker'),
        ),
    ]
